name = "classmate-catchup"
main = "worker/index.js"
compatibility_date = "2025-05-01"

[[d1_databases]]
binding = "DB"
database_name = "classmate-catchup-db"
database_id = "1cc65fd5-25fb-4f4b-ae66-c30d9eaa7125"
